### PR TITLE
Miscellaneous fixes for `bin/install.sh`

### PR DESCRIPTION
**Pull request by dongcarl**

### CODE REVIEW

**Comment by jamesob** [comment]
Thanks for the changes! Sadly I think the second commit needs to be reworked or dropped. The reason I did that hacky sudo stuff in the first place is to facilitate environments where sudo doesn't work right (e.g. the docker container in Travis that is currently failing to run the script).

If you can figure out a way to square your changes with Travis, I think we're okay to merge.

**Comment by MarcoFalke** [comment]
The base branch is failing travis, so the issue might be unrelated

**Comment by jamesob** [comment]
> The base branch is failing travis, so the issue might be unrelated

In this case it isn't; you can see in the travis output that there are a bunch of lines like
```
./bin/install.sh: line 13: sudo: command not found
```

**Comment by dongcarl** [comment]
Done!

**Comment by jamesob** [comment]
Thanks! I'll have to fix travis soon...

**Pull request merged**
